name: bump version
on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  bump-version:
    name: "Bump Version"
    runs-on: ubuntu-latest
    needs: [check-coding-style]
    steps:
      - run: Check needs
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
      - name: "Checkout source code"
        uses: "actions/checkout@v4"
        with:
          ref: ${{ github.ref }}
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Automated Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
        with:
          version-type: "minor"
          target-branch: "main"
          tag-prefix: "v"
          commit-message: "ci: bumps version to {{version}}"
